### ISSUE TITLE
Once the simulation is ready, ¿how do we project it to the table?

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScienceLab-GDL/cityscope-ccu#2]
Luis mentioned that they have used "keystoning". We need to check if it is a way to implement that using GAMA.

**Comment by agrignard** [comment]
Hi @gamalielpalomo , yes the keystone is an embedded feature in GAMA since 2016. Most of the Tangible Interface made with GAMA (e.g MIT CityScope Volpe table) are  made using  the keystone feature of GAMA.

You can refer to the GAMA documentation for more information here:
https://gama-platform.org/wiki/Displays#opengl-displays

**Comment by gamalielpalomo** [comment]
Okay, thank you!

**Comment by agrignard** [comment]
To set up correctly the visualization depending on your settings you will need to use the same syntax as the volpe table that you can find here
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/CityScope/CityScope_main.gaml

**Comment by agrignard** [comment]
As you are using a screen to display the simulation I am not sure the issue is relevant.

I let you close it

**Comment by gamalielpalomo** [comment]
Well, this issue can be closed as the gama model now runs fullscreen and we already tested it on the screen.
